version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_MasterUuid
    restart: always
    ports:
      - "5001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - uuid-mysql-data:/var/lib/mysql
      
  flask_app:
    build: 
      dockerfile: ./src/Dockerfile
      context: .
    container_name: MasterUuid_API
    restart: always
    ports:
      - "6000:6000"

volumes:
  uuid-mysql-data:
