version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: MasterUuid
    restart: always
    ports:
      - "8090:80"  # Verbindt de poort 8080 van de host met poort 80 van de container
    environment:
      PMA_HOST: mysql_masteruuid  # De naam van de MySQL-server (standaard 'mysql' voor Docker)
      PMA_PORT: 50001   # De poort van de MySQL-server

  mysql:
    image: mysql:5.7
    container_name: mysql_MasterUuid
    restart: always
    ports:
      - "50001:3306"
    environment:
      PMA_HOST: mysql_masteruuid
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: 
      dockerfile: ./src/Dockerfile
      context: .
    container_name: MasterUuid_API
    restart: always
    ports:
      - "6000:6000"

volumes:
  mysql_data:
